### ISSUE TITLE
Carbon removal and carbon storage

### ISSUE THREAD

**Issue by jmtlawrie** [Planetary-Technologies/MRV#7]
Hello!

First of all I would like to commend the publishing of your MRV for scrutiny from external parties. I think it shows your confidence in your chosen approach and I believe it will ultimately lead to improved outcomes. To this end I'd like to raise a few questions referencing version 2 of this MRV document.

Please read my questions bearing in mind the in context of sentence one of Planetary Technologies' stated mission (on the [website](https://www.planetarytech.com/aboutus/)): "Planetary enhances the ocean’s natural ability to fight climate change through carbon dioxide removal and **storage**."

Referencing section 3 "Calculation of net Carbon Dioxide Removal (CDR)" on page 3: It is clearly stated that CDR is calculated within 1 year of adding MH. Given it is in the name, these detailed calculations and stated uncertainties give a good idea of the potential of the technology for **removal** of carbon dioxide. Section 7 "Permanence of sequestration" suggests that over a 10000 year period after the addition of alkaline carbon via this technology, at best half of what was removed will be permanently deposited as sediment whilst the other half returns to the atmosphere.

**Could you publish some additional analysis suggesting the expected trend in cumulative **_storage_** per quantity of _**removal**_ over a relevant time-span (maybe 1 year, 10 year, 100 year, 1000 year, 10000 year)?**

----

I acknowledge that Planetary Technologies aims to sell carbon **removal** credits, rather than carbon removal and **storage** credits as is clearly stated on page 8.

**Nonetheless, what is Planetary Technologies view of the idea that for a credit sold for a tonne of CO2 removed that (at best) is expected to _store only half_ a tonne as late as 10000 years later may be important information for climate-conscious customers, who may come to feel mislead by the first sentence of planetary's mission?**

----

One way around this would be perhaps to focus on the precipitation of CaCO3 directly via the addition of alkali, as discussed in the report on page 18.

Treating wastewater or seawater to precipitate CaCO3 releasing sediment that is sequestered for millions of years, as well as capturing the released gaseous high-concentration CO2 stream and storing this would seem to allow the technology to be just as effective at removal of CO2 as it is at **storing** it. Furthermore, once this process is complete, there stated risks outlined in section 8 "Reversal risks" on page 10 would seem not to apply any more.

There must surely be downsides to this approach, such as increased complexity and therefore cost. However perhaps the climate-conscious customer would pay even more for a carbon credit guaranteeing not only net CO2 removal, but also that this CO2 will stay removed.

**Does Planetary Technologies think it would be reassuring to see this concept discussed in greater detail with the case for ruling out this (or other approaches more focused on storage, rather than relatively short term storage) clearly presented?**

----

I hope that some of these thoughts help a little bit with your mission and would like to again commend that you have published your workings, something atypical for industry practice (in my limited individual experience).

Thank you for your time and good luck!

Regards,

Joe

**Comment by ghrau** [comment]
Dear Joe,
Thanks for your interest in our MRV. 
Your comment:  ""Permanence of sequestration" suggests that over a 10000 year period after the addition of alkaline carbon via this technology, at best half of what was removed will be permanently deposited as sediment whilst the other half returns to the atmosphere." is incorrect. The mean residence time of alkaline C in seawater is 100,000yrs = 10^5 yrs. So if the oceans contain about 34,000 Gt of alkaline C and looses 0.3 GtC/yr due to CaCO3 precipitation and an equal amount as CO2, and the system is in steady state, we should expect to loose about 0.0018%/yr of the alkalinity we add. We are happy to discount our C credits by half that amount each year, 0.0009%/yr (about half of the lose is permanetly stored as CaCO3), if that is demanded by our customers. 
As for storing as solid metal carbonates vs as dissolved ocean alkalinity, while the former is "permanent", the latter is 60-70% more efficient in CDR per mol of alkalinity over the next many millennia. Plus it helps counter ocean acidification. This is why we prefer OAE over mineral carbonate formation, but happy to accommodate customer wishes as you suggest. 
Thanks again for your interest and concerns.
Regards,
Greg Rau

**Comment by jmtlawrie** [comment]
Dear Greg,

thank you for your feedback to my questions. I acknowledge that I mistyped 10^5 years as 10000, rather than 100000 years - apologies.

You wrote: "As for storing as solid metal carbonates vs as dissolved ocean alkalinity, while the former is "permanent", the latter is 60-70% more efficient in CDR per mol of alkalinity over the next many millennia." - I think it would be a great addition to the MRV (or its supporting materials) to show the workings of this calculation to help people avoid confusion.

You also wrote "This is why we prefer OAE over mineral carbonate formation, but happy to accommodate customer wishes as you suggest." - if the efficiency of the process is 60...70% poorer and the storage (as opposed to removal) aspects are essentially no different on human timescales, why would you allow a customer to make a mistake, wasting valuable resources, slowing down your way to removing meaningful quantities of greenhouse gas emissions from the atmosphere?

Finally you reminded me that: "Plus it (this technology) helps counter ocean acidification.", but this seems to be directly contradicted by this sentence on page 9 in section 6 "Additional considerations - Consideration and Monitoring of Ecological Safety":
    - "Slow MH dissolution means that general dilution of an alkalinized effluent in the marine environment will greatly outpace the chemical changes induced by the MH addition."

Will adding MH effect chemical changes in the marine environment (such as promoting coral growth) or will it dilute so fast that it will not have any affects on the marine environment, leaving the acidication of the ocean not measurably different than it was before any MH was added?

----

It probably that it seems like I am reading too much into small aspects of this MRV, but given how important it is for making informed decicisions about the future of this technology (for your potential customers and the planet as a whole), I'm sure you feel that scrutiny is justified and welcome - otherwise I do not think you would have published your MRV in the first place, something I once again can only commend.

Many thanks
Joe

**Comment by ghrau** [comment]
Thanks for your continuing interest, Joe.
As for "...why would you allow a customer to make a mistake..." re make mineral carbonate vs more efficeint OAE, not all of our customers are near an ocean. So to accomodate them we are willing to not let "better" be the enemy of the "good".
As for slow dissolving MH, we use it to avoid pH spikes. Just as it's bad for ocean pH to rapidly go down, so too is it bad for it to rapidly go up.  So MH offers a times release aspect that does raise pH but in a dilute and slow way that won't hugely perturb ocean chem and bio. I have a feeling this is why MH (milk of magnesia) is ingested by millions to rebalance human gut chem and bio. You won't want to consume the equivalent in the form of NaOH!
We will take your comments and suggestions  into consideration in our V3.0 MRV rewrite.
Thanks again,
Greg Rau
